---
apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: simple-hosted-pipeline
spec:
  params:
    - name: target-environment
  resourcetemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: simple-hosted-pipeline-$(uid)-pvc
      spec:
        resources:
          requests:
            storage: 5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: simple-hosted-pipeline-$(uid)
      spec:
        pipelineRef:
          name: simple-hosted-pipeline
        params:
          - name: target-environment
            value: $(params.target-environment)
        workspaces:
          - name: pipeline-ws
            persistentVolumeClaim:
              claimName: simple-hosted-pipeline-$(uid)-pvc
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: manual-run
spec:
  params:
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: manual-run
spec:
  triggers:
    - binding:
        name: manual-run
      template:
        name: simple-hosted-pipeline
